//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jCtrl.Shipping.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5C9E024EAE0895B8")]
        public string UPS_AccessKey_BAU {
            get {
                return ((string)(this["UPS_AccessKey_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("029214")]
        public string UPS_AccountNo_BAU {
            get {
                return ((string)(this["UPS_AccountNo_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BC9E024653FD7BE3")]
        public string UPS_AccessKey_SNG {
            get {
                return ((string)(this["UPS_AccessKey_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9W7277")]
        public string UPS_AccountNo_SNG {
            get {
                return ((string)(this["UPS_AccountNo_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2C9E0248F9C3D228")]
        public string UPS_AccessKey_SNH {
            get {
                return ((string)(this["UPS_AccessKey_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80044Y")]
        public string UPS_AccountNo_SNH {
            get {
                return ((string)(this["UPS_AccountNo_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_BAU {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_Limit_BAU {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_Limit_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Percentage_BAU {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Percentage_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_BAU {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_Limit_BAU {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_Limit_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Percentage_BAU {
            get {
                return ((decimal)(this["UPS_International_Margin_Percentage_BAU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_SND {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_Limit_SND {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_Limit_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Percentage_SND {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Percentage_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_SND {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_Limit_SND {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_Limit_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Percentage_SND {
            get {
                return ((decimal)(this["UPS_International_Margin_Percentage_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_SNG {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_Limit_SNG {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_Limit_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Percentage_SNG {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Percentage_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_SNG {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_Limit_SNG {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_Limit_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Percentage_SNG {
            get {
                return ((decimal)(this["UPS_International_Margin_Percentage_SNG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_SNH {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Fixed_Limit_SNH {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Fixed_Limit_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_Domestic_Margin_Percentage_SNH {
            get {
                return ((decimal)(this["UPS_Domestic_Margin_Percentage_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_SNH {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Fixed_Limit_SNH {
            get {
                return ((decimal)(this["UPS_International_Margin_Fixed_Limit_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal UPS_International_Margin_Percentage_SNH {
            get {
                return ((decimal)(this["UPS_International_Margin_Percentage_SNH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2C9E0248F9C3D228")]
        public string UPS_AccessKey_SND {
            get {
                return ((string)(this["UPS_AccessKey_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80044Y")]
        public string UPS_AccountNo_SND {
            get {
                return ((string)(this["UPS_AccountNo_SND"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40404101")]
        public string Chronoship_UserId {
            get {
                return ((string)(this["Chronoship_UserId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("531124")]
        public string Chronoship_UserPwd {
            get {
                return ((string)(this["Chronoship_UserPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("389SNGBA5970")]
        public string USPS_UserId {
            get {
                return ((string)(this["USPS_UserId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("552PB00ON077")]
        public string USPS_UserPwd {
            get {
                return ((string)(this["USPS_UserPwd"]));
            }
        }
    }
}
