//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jCtrl.Shipping.UPS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jCtrl.Shipping.UPS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;AccessRequest xml:lang=&quot;en-US&quot;&gt;
        /// 	&lt;AccessLicenseNumber&gt;#accesskey&lt;/AccessLicenseNumber&gt;
        ///	&lt;UserId&gt;#userid&lt;/UserId&gt;
        ///	&lt;Password&gt;#password&lt;/Password&gt;
        ///&lt;/AccessRequest&gt;
        ///&lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;RatingServiceSelectionRequest xml:lang=&quot;en-US&quot;&gt;
        ///  &lt;Request&gt;
        ///    &lt;TransactionReference&gt;
        ///      &lt;CustomerContext&gt;#requestreference&lt;/CustomerContext&gt;
        ///      &lt;XpciVersion&gt;1.0&lt;/XpciVersion&gt;
        ///    &lt;/TransactionReference&gt;
        ///	&lt;RequestAction&gt;Rate&lt;/RequestAction&gt;
        ///	&lt;RequestOption&gt;Shop&lt;/RequestOption&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsGetShippingRatesRequest {
            get {
                return ResourceManager.GetString("UpsGetShippingRatesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;AccessRequest xml:lang=&quot;en-US&quot;&gt;
        /// 	&lt;AccessLicenseNumber&gt;#accesskey&lt;/AccessLicenseNumber&gt;
        ///	&lt;UserId&gt;#userid&lt;/UserId&gt;
        ///	&lt;Password&gt;#password&lt;/Password&gt;
        ///&lt;/AccessRequest&gt;
        ///&lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;RatingServiceSelectionRequest xml:lang=&quot;en-US&quot;&gt;
        ///  &lt;Request&gt;
        ///    &lt;TransactionReference&gt;
        ///      &lt;CustomerContext&gt;#requestreference&lt;/CustomerContext&gt;
        ///      &lt;XpciVersion&gt;1.0&lt;/XpciVersion&gt;
        ///    &lt;/TransactionReference&gt;
        ///	&lt;RequestAction&gt;Rate&lt;/RequestAction&gt;
        ///	&lt;RequestOption&gt;Shop&lt;/RequestOption&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsGetShippingRatesRequest_DIMS {
            get {
                return ResourceManager.GetString("UpsGetShippingRatesRequest_DIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;AccessRequest xml:lang=&quot;en-US&quot;&gt;
        ///  &lt;AccessLicenseNumber&gt;#accesskey&lt;/AccessLicenseNumber&gt;
        ///  &lt;UserId&gt;#userid&lt;/UserId&gt;
        ///  &lt;Password&gt;#password&lt;/Password&gt;
        ///&lt;/AccessRequest&gt;
        ///&lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;RatingServiceSelectionRequest xml:lang=&quot;en-US&quot;&gt;
        ///  &lt;Request&gt;
        ///    &lt;TransactionReference&gt;
        ///      &lt;CustomerContext&gt;#requestreference&lt;/CustomerContext&gt;
        ///      &lt;XpciVersion&gt;1.0&lt;/XpciVersion&gt;
        ///    &lt;/TransactionReference&gt;
        ///    &lt;RequestAction&gt;Rate&lt;/RequestAction&gt;
        ///    &lt;RequestOption&gt;#requestoption&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsGetShippingRatesRequest_Packages {
            get {
                return ResourceManager.GetString("UpsGetShippingRatesRequest_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;AccessRequest xml:lang=&quot;en-US&quot;&gt;
        /// 	&lt;AccessLicenseNumber&gt;#accesskey&lt;/AccessLicenseNumber&gt;
        ///	&lt;UserId&gt;#userid&lt;/UserId&gt;
        ///	&lt;Password&gt;#password&lt;/Password&gt;
        ///&lt;/AccessRequest&gt;
        ///&lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;RatingServiceSelectionRequest xml:lang=&quot;en-US&quot;&gt;
        ///  &lt;Request&gt;
        ///    &lt;TransactionReference&gt;
        ///      &lt;CustomerContext&gt;#requestreference&lt;/CustomerContext&gt;
        ///      &lt;XpciVersion&gt;1.0&lt;/XpciVersion&gt;
        ///    &lt;/TransactionReference&gt;
        ///	&lt;RequestAction&gt;Rate&lt;/RequestAction&gt;
        ///	&lt;RequestOption&gt;Shop&lt;/RequestOption&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsGetShippingRatesRequest_USA {
            get {
                return ResourceManager.GetString("UpsGetShippingRatesRequest_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Package&gt;
        ///  &lt;PackagingType&gt;
        ///    &lt;Code&gt;02&lt;/Code&gt;
        ///  &lt;/PackagingType&gt;
        ///  &lt;Dimensions&gt;
        ///    &lt;UnitOfMeasurement&gt;
        ///      &lt;Code&gt;CM&lt;/Code&gt;
        ///    &lt;/UnitOfMeasurement&gt;
        ///    &lt;Length&gt;#lengthCms&lt;/Length&gt;
        ///    &lt;Width&gt;#widthCms&lt;/Width&gt;
        ///    &lt;Height&gt;#heightCms&lt;/Height&gt;
        ///  &lt;/Dimensions&gt;
        ///  &lt;PackageWeight&gt;
        ///    &lt;UnitOfMeasurement&gt;
        ///      &lt;Code&gt;KGS&lt;/Code&gt;
        ///    &lt;/UnitOfMeasurement&gt;
        ///    &lt;Weight&gt;#weightkgs&lt;/Weight&gt;
        ///  &lt;/PackageWeight&gt;
        ///  &lt;AdditionalHandling/&gt;
        ///  &lt;LargePackageIndicator/&gt;
        ///&lt;/Package&gt;.
        /// </summary>
        internal static string UpsPackage {
            get {
                return ResourceManager.GetString("UpsPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Package&gt;
        ///  &lt;PackagingType&gt;
        ///    &lt;Code&gt;02&lt;/Code&gt;
        ///  &lt;/PackagingType&gt;
        ///  &lt;PackageWeight&gt;
        ///    &lt;UnitOfMeasurement&gt;
        ///      &lt;Code&gt;KGS&lt;/Code&gt;
        ///    &lt;/UnitOfMeasurement&gt;
        ///    &lt;Weight&gt;#weightkgs&lt;/Weight&gt;
        ///  &lt;/PackageWeight&gt;
        ///  &lt;AdditionalHandling/&gt;
        ///&lt;/Package&gt;.
        /// </summary>
        internal static string UpsPackage_WithoutDims {
            get {
                return ResourceManager.GetString("UpsPackage_WithoutDims", resourceCulture);
            }
        }
    }
}
